DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "AC"

  normalize_d_embed: True

  # apply_g_sn: True
  # apply_d_sn: True
LOSS:
  adv_loss: "hinge"
  cond_lambda: 1.0


