DATA:
  name: "CIFAR100"
  img_size: 32
  num_classes: 100
MODEL:
  g_cond_mtd: "cBN"
  d_cond_mtd: "AC"
  
  backbone: "simple_resnet"   #resnet_simple

  # apply_g_sn: True
  # apply_d_sn: True

LOSS:
  adv_loss: "hinge"
  cond_lambda: 1.0
